# Generated by Django 4.0.6 on 2023-01-26 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('Appointments_id', models.AutoField(primary_key=True, serialize=False)),
                ('Appointments_date', models.DateField(default='')),
                ('Appointments_time', models.CharField(default='', max_length=100)),
                ('Appointments_type', models.CharField(default='', max_length=50)),
                ('order_id', models.CharField(default='', max_length=100)),
                ('patient_name', models.CharField(default='Patient', max_length=100)),
                ('patient_mobile', models.CharField(default='123456789', max_length=100)),
                ('appointment_status', models.CharField(default='pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=200)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Subject', models.CharField(default='', max_length=250)),
                ('Message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='diagnostic_appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(default='', max_length=100)),
                ('Appointments_date', models.DateField(default='')),
                ('Patient_name', models.CharField(default='', max_length=100)),
                ('Patient_mobile', models.BigIntegerField(default='')),
                ('Patient_email', models.EmailField(default='', max_length=254)),
                ('Patient_gender', models.CharField(default='', max_length=50)),
                ('Patient_DOB', models.DateField(default='')),
                ('Patient_pincode', models.BigIntegerField(default='')),
                ('Patient_adress', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='diagnostic_test_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField(default=200)),
                ('image', models.ImageField(default='', upload_to='dmz_imgs/diagnostic_test_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_email', models.CharField(max_length=50, unique=True)),
                ('doctor_DOB', models.DateField()),
                ('doctor_sex', models.CharField(max_length=10)),
                ('doctor_mobile', models.BigIntegerField(unique=True)),
                ('doctor_address', models.CharField(max_length=200)),
                ('doctor_city', models.CharField(max_length=50)),
                ('doctor_state', models.CharField(max_length=50)),
                ('doctor_zip', models.IntegerField()),
                ('doctor_userName', models.CharField(max_length=50, unique=True)),
                ('doctor_pass', models.CharField(default='', max_length=100, unique=True)),
                ('doctor_country', models.CharField(default='', max_length=100)),
                ('doctor_area', models.CharField(default='', max_length=100)),
                ('doctor_self', models.TextField(default='', max_length=100)),
                ('doctor_Awards', models.CharField(default='', max_length=500)),
                ('doctor_Awards_year', models.CharField(default='', max_length=500)),
                ('hosptial_name', models.CharField(default='', max_length=100)),
                ('hospital_address', models.CharField(default='', max_length=100)),
                ('hosptial_area', models.CharField(default='', max_length=100)),
                ('hosptial_city', models.CharField(default='', max_length=100)),
                ('hosptial_state', models.CharField(default='', max_length=100)),
                ('hosptial_country', models.CharField(default='', max_length=100)),
                ('hosptial_pincode', models.CharField(default='', max_length=100)),
                ('hosptial_telephone', models.BigIntegerField()),
                ('doctor_category', models.CharField(default='doctor', max_length=50)),
                ('doctor_profile', models.ImageField(default='null', upload_to='dmz_imgs/doctor/images/profile')),
                ('doctor_certificate', models.ImageField(default='null', upload_to='dmz_imgs/doctor/images/certificates')),
                ('doctor_qualifcation', models.CharField(default='doctor', max_length=100)),
                ('doctor_fee', models.BigIntegerField(default='100')),
                ('advance_appointment', models.IntegerField(default='1')),
                ('time_Slots', models.CharField(default='', max_length=1000)),
                ('payment_satus', models.CharField(default='unpaid', max_length=50)),
                ('Experience', models.IntegerField(default=5)),
                ('joining_date', models.DateTimeField(default=datetime.datetime(2023, 1, 26, 18, 44, 54, 198455))),
                ('status', models.CharField(default='Logout', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='homeCare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('service', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=50)),
                ('Reason', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='homeCare_page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Home_Care_Service', models.CharField(default='', max_length=100)),
                ('price', models.BigIntegerField(default=500)),
                ('Home_Care_Service_image', models.ImageField(default='', upload_to='dmz_imgs/HomeCare/')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=100)),
                ('Lab_Name', models.CharField(default='', max_length=100)),
                ('Educations', models.CharField(default='', max_length=100)),
                ('Id_Proof', models.ImageField(default='', upload_to='dmz_imgs/Lab/id_proof/')),
                ('license', models.ImageField(default='', upload_to='dmz_imgs/Lab/license/')),
                ('Lab_Iamge', models.ImageField(default='', upload_to='dmz_imgs/Lab/Lab_iamge/')),
                ('UserName', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=150)),
                ('Address', models.CharField(default='', max_length=500)),
                ('City', models.CharField(default='', max_length=100)),
                ('State', models.CharField(default='', max_length=100)),
                ('Zip', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.CharField(max_length=50, unique=True)),
                ('patient_DOB', models.DateField(null=True)),
                ('patient_sex', models.CharField(max_length=10)),
                ('patient_mobile', models.BigIntegerField(unique=True)),
                ('patient_Blood', models.CharField(default='A+', max_length=50)),
                ('patient_profile', models.ImageField(default='', upload_to='dmz_imgs/patient/images/profile')),
                ('patient_address', models.CharField(max_length=200)),
                ('patient_city', models.CharField(max_length=50)),
                ('patient_state', models.CharField(max_length=50)),
                ('patient_zip', models.IntegerField()),
                ('patient_userName', models.CharField(default='', max_length=50, unique=True)),
                ('patient_pass', models.CharField(default='', max_length=100)),
                ('patient_area', models.CharField(default='', max_length=50)),
                ('patient_country', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='Logout', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QNA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(default='', max_length=500)),
                ('Answer', models.CharField(default='Pending', max_length=500)),
                ('Email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='specilaity',
            fields=[
                ('specilaity_category', models.CharField(max_length=200)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='dmz_imgs/speciality_icon/')),
            ],
        ),
        migrations.CreateModel(
            name='Tele',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('service', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('status', models.CharField(default='pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsRatings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(default='', max_length=100)),
                ('health_concern', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('recommend_doctor', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now_add=True)),
                ('doctorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Last_login', models.DateTimeField(default='')),
                ('total_login', models.IntegerField(default=1, null=True)),
                ('Patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Last_login', models.DateTimeField(default='')),
                ('total_login', models.IntegerField(default=0)),
                ('Doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=200, null=True)),
                ('medicine', models.CharField(max_length=500, null=True)),
                ('appointments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.appointments')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('Bill_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('Payment', models.IntegerField(default=1)),
                ('order_id', models.CharField(default='', max_length=100)),
                ('Payment_id', models.CharField(max_length=100, null=True)),
                ('signature', models.CharField(max_length=200, null=True)),
                ('Bill_date', models.DateTimeField(default=datetime.datetime(2023, 1, 26, 18, 44, 54, 199452))),
                ('payment_status', models.BooleanField(default=False)),
                ('appointments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.appointments')),
            ],
        ),
        migrations.CreateModel(
            name='Appointmnet_Bill',
            fields=[
                ('Bill_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='', max_length=100)),
                ('Payment_id', models.CharField(max_length=100, null=True)),
                ('signature', models.CharField(max_length=200, null=True)),
                ('Payment', models.IntegerField(default=0)),
                ('Bill_date', models.DateTimeField(default='')),
                ('Doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.doctor')),
                ('Patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='Doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.doctor'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.patient'),
        ),
    ]
