# Generated by Django 4.0.6 on 2023-01-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Bill_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
