# Generated by Django 4.0.6 on 2023-02-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0003_remove_doctor_payment_satus_doctor_security_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_login',
            name='total_login',
            field=models.IntegerField(default=1),
        ),
    ]
