# Generated by Django 4.0.6 on 2023-02-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0004_alter_doctor_login_total_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='overall_rating',
            field=models.FloatField(default=0),
        ),
    ]
