# Generated by Django 4.0.6 on 2023-02-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0005_doctor_overall_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
