# Generated by Django 4.0.6 on 2023-02-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0006_pageview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_pass',
            new_name='password',
        ),
    ]
