# Generated by Django 4.0.6 on 2023-02-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0007_rename_patient_email_patient_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_pass',
            new_name='password',
        ),
    ]
