# Generated by Django 4.0.6 on 2023-02-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0008_rename_doctor_email_doctor_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_mobile',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='patient',
            name='Security_Answer',
            field=models.CharField(default='Drmedizone', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='Security_Question',
            field=models.CharField(default='What is your name ?', max_length=500),
        ),
    ]
