# Generated by Django 4.0.6 on 2023-02-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0009_rename_doctor_mobile_doctor_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecare',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.patient'),
        ),
    ]
