# Generated by Django 4.0.6 on 2023-02-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0010_homecare_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
