# Generated by Django 4.0.6 on 2023-02-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0011_qna_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.patient'),
        ),
    ]
