# Generated by Django 4.0.6 on 2023-03-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0012_qna_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='Cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
