# Generated by Django 4.0.6 on 2023-04-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0013_appointments_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic_appointment',
            name='Patient_DOB',
        ),
        migrations.AddField(
            model_name='diagnostic_appointment',
            name='Appointments_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic_appointment',
            name='Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic_appointment',
            name='Patient_adress',
            field=models.CharField(default='', max_length=300),
        ),
    ]
