# Generated by Django 4.0.6 on 2023-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0014_remove_diagnostic_appointment_patient_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='combo_diagnostic_test_list',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='dmz_imgs/combo_diagnostic_test_img/')),
            ],
        ),
    ]
