# Generated by Django 4.0.6 on 2023-04-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0015_combo_diagnostic_test_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo_diagnostic_test_list',
            name='Test_count',
            field=models.IntegerField(default=2),
        ),
    ]
