# Generated by Django 4.0.6 on 2023-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0016_combo_diagnostic_test_list_test_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo_diagnostic_test_list',
            name='Age_Group',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='combo_diagnostic_test_list',
            name='Gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='combo_diagnostic_test_list',
            name='What_preparation_is_needed_for_this_Checkup',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='combo_diagnostic_test_list',
            name='Who_should_book_this_checkup',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diagnostic_test_list',
            name='Age_Group',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic_test_list',
            name='Gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic_test_list',
            name='What_preparation_is_needed_for_this_Checkup',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diagnostic_test_list',
            name='Who_should_book_this_checkup',
            field=models.TextField(null=True),
        ),
    ]
