# Generated by Django 4.0.6 on 2023-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0017_combo_diagnostic_test_list_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_test_list',
            name='Home_visit',
            field=models.BooleanField(default=True),
        ),
    ]
