# Generated by Django 4.0.6 on 2023-04-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0019_dignostic_test_cart_dignostic_test_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic_appointment',
            name='test',
        ),
    ]
