# Generated by Django 4.0.6 on 2023-04-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0020_remove_diagnostic_appointment_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_appointment',
            name='order_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnostic_appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMZ.patient'),
        ),
    ]
