# Generated by Django 4.0.6 on 2023-04-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0021_diagnostic_appointment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_appointment',
            name='SingleTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Single_Lab_tests', to='DMZ.diagnostic_test_list'),
        ),
    ]
