# Generated by Django 4.0.6 on 2023-04-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0022_diagnostic_appointment_singletest'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_appointment',
            name='ComboTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Como_Lab_tests', to='DMZ.combo_diagnostic_test_list'),
        ),
        migrations.AlterField(
            model_name='diagnostic_appointment',
            name='SingleTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_Lab_tests', to='DMZ.diagnostic_test_list'),
        ),
    ]
