# Generated by Django 4.0.6 on 2023-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0023_diagnostic_appointment_combotest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dignostic_test_cartitems',
            name='order',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
