# Generated by Django 4.0.6 on 2023-04-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0024_dignostic_test_cartitems_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DignoBill',
            fields=[
                ('Orders_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('Payment_id', models.CharField(max_length=100, null=True)),
                ('signature', models.CharField(max_length=500, null=True)),
                ('price', models.FloatField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bill_Lab_tests', to='DMZ.diagnostic_appointment')),
            ],
        ),
    ]
