# Generated by Django 4.0.6 on 2023-04-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0025_dignobill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dignobill',
            name='Test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bill_Lab_tests', to='DMZ.diagnostic_appointment'),
        ),
    ]
