# Generated by Django 4.0.6 on 2023-04-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0026_alter_dignobill_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic_appointment',
            name='order_id',
        ),
    ]
