# Generated by Django 4.0.6 on 2023-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0027_remove_diagnostic_appointment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_appointment',
            name='order_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
