# Generated by Django 4.0.6 on 2023-04-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0028_diagnostic_appointment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dignostic_test_cartitems',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
