# Generated by Django 4.0.6 on 2023-04-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0030_dignobill_testcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dignobill',
            name='TestCart',
        ),
    ]
