# Generated by Django 4.0.6 on 2023-04-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0031_remove_dignobill_testcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic_appointment',
            name='ComboTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cart_Bill_Lab_tests', to='DMZ.dignostic_test_cart'),
        ),
    ]
