# Generated by Django 4.0.6 on 2023-04-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0032_alter_diagnostic_appointment_combotest'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_appointment',
            name='CartTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cart_Bill_Lab_tests', to='DMZ.dignostic_test_cart'),
        ),
        migrations.AlterField(
            model_name='diagnostic_appointment',
            name='ComboTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Como_Lab_tests', to='DMZ.combo_diagnostic_test_list'),
        ),
    ]
