# Generated by Django 4.0.6 on 2023-04-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0033_diagnostic_appointment_carttest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_appointment',
            name='visiting',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
