# Generated by Django 4.0.6 on 2023-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0034_diagnostic_appointment_visiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
