# Generated by Django 4.0.6 on 2023-04-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0035_bill_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_appointment',
            name='Cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
