# Generated by Django 4.0.6 on 2023-04-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0036_diagnostic_appointment_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.specilaity'),
        ),
    ]
