# Generated by Django 4.0.6 on 2023-04-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0037_doctor_doctor_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='Message',
            field=models.TextField(default=''),
        ),
    ]
