# Generated by Django 4.0.6 on 2023-04-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0038_alter_contact_us_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_zip',
            field=models.BigIntegerField(),
        ),
    ]
