# Generated by Django 4.0.6 on 2023-04-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0039_alter_doctor_doctor_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMZ.patient')),
            ],
        ),
    ]
