# Generated by Django 4.0.6 on 2023-04-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0040_patientreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='upload',
            field=models.FileField(upload_to='dmz_imgs/doctor/Reports'),
        ),
    ]
