# Generated by Django 4.0.6 on 2023-04-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0041_alter_patientreport_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='patientName',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
