# Generated by Django 4.0.6 on 2023-01-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_products_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
