# Generated by Django 4.0.6 on 2023-02-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_brand_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Out For Delivery', 'Out For Delivery'), ('Order delivered', 'Order delivered')], default='Order Received', max_length=50),
        ),
    ]
