# Generated by Django 4.0.6 on 2023-02-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMZ', '0003_remove_doctor_payment_satus_doctor_security_answer_and_more'),
        ('medicine', '0004_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='DMZ.patient')),
            ],
        ),
        migrations.CreateModel(
            name='wishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productItem', to='medicine.products')),
                ('WishlistProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='medicine.wishlist')),
            ],
        ),
    ]
