# Generated by Django 4.0.6 on 2023-02-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='overall_rating',
            field=models.FloatField(default=0),
        ),
    ]
