# Generated by Django 4.0.6 on 2023-04-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_products_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Expected_Total_medicines',
            field=models.IntegerField(default=1000),
        ),
    ]
