# Generated by Django 4.0.6 on 2023-04-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_products_expected_total_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Qunatity',
            field=models.IntegerField(default=1),
        ),
    ]
