# Generated by Django 4.0.6 on 2023-04-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_cartitem_qunatity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='uses',
            field=models.TextField(),
        ),
    ]
